# Generated by Django 6.0.2 on 2026-05-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('recipients', models.TextField(help_text='Comma- or newline-separated recipient addresses')),
                ('bcc', models.TextField(blank=True, null=True)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.TextField(blank=True, help_text='JSON or comma-separated attachment metadata', null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing email',
                'verbose_name_plural': 'Outgoing emails',
                'ordering': ('-sent_at',),
            },
        ),
    ]
