# Generated by Django 4.0.6 on 2022-08-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='auth.group', verbose_name='Group')),
            ],
            options={
                'ordering': ['type', 'group', 'user'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload/organizations/', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telephone Number')),
                ('website', models.URLField(blank=True, help_text='Include Protocol i.E. https://example.com', null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('members', models.ManyToManyField(blank=True, related_name='organization_memberships', to='organizations.membership', verbose_name='Members')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('admin', models.BooleanField(blank=True, default=None, null=True, verbose_name='Admin')),
                ('default', models.BooleanField(blank=True, default=None, null=True, verbose_name='Default')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', '-admin', '-default', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.membershiptype', verbose_name='Membership Type'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='name_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.UniqueConstraint(fields=('organization', 'admin'), name='admin_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.UniqueConstraint(fields=('organization', 'default'), name='default_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(('admin', False), _negated=True), name='admin_true_or_null'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(('default', False), _negated=True), name='default_true_or_null'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin', True), ('default__isnull', True)), ('admin__isnull', True), _connector='OR'), name='admin_not_default'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'organization'), name='unique_group_organization'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('group__isnull', True), _negated=True), name='group_or_user'),
        ),
    ]
