# Generated by Django 4.0.6 on 2022-08-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('test', 'Test Permission')]},
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions'),
        ),
    ]
