# Generated by Django 4.0.9 on 2023-02-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdummyuser',
            name='claimed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_org_dummy_users', to='accounts.baseuser', verbose_name='Claimed by'),
        ),
    ]
