# Generated by Django 4.0.6 on 2022-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Include Protocol i.E. https://example.com', null=True, verbose_name='Website'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'organization'), name='unique_group_organization'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('group__isnull', True), _negated=True), name='group_or_user'),
        ),
    ]
