# Generated by Django 4.0.9 on 2023-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationdummyuser_claimed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='A maximum of 1000 characters is allowed', max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
