# Generated by Django 4.0.6 on 2022-09-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('admin', 'manage all organizations'), ('create_shift', 'create shifts for the organization')]},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
    ]
