# Generated by Django 4.0.6 on 2022-08-04 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'default_permissions': (), 'ordering': ['type', 'group', 'user']},
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'admin', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.membershiptype', verbose_name='Membership Type'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.UniqueConstraint(fields=('organization', 'admin'), name='only_one_admin'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.UniqueConstraint(fields=('organization', 'default'), name='only_one_default'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin', True), ('default', False)), ('admin', False), _connector='OR'), name='admin_not_default'),
        ),
    ]
