# Generated by Django 4.0.6 on 2022-09-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'default_permissions': (), 'ordering': ['organization', '-admin', '-default', 'name'], 'permissions': [('edit_organization', 'edit organization details'), ('see_members', 'see members of the organization'), ('see_statistics', 'see shift participation statistics'), ('edit_membership_types', 'create and update membership types for the organization'), ('edit_members', 'add and remove members for the organization'), ('edit_event', 'create and update events for the organization'), ('edit_recurring_shift', 'create and update recurring shifts for the organization'), ('edit_shift_template', 'create and update shifts templates for the organization'), ('edit_shift', 'create and update shifts for the organization'), ('remove_others_from_shifts', 'remove others from shifts'), ('add_non_members_to_shifts', 'add other users that are not members of the organization to shifts'), ('add_members_to_shifts', 'add other organization members to shifts'), ('participate_in_shift', 'participate in shifts')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('admin', 'manage all organizations')]},
        ),
    ]
