# Generated by Django 4.0.6 on 2022-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_options_alter_shifter_options'),
        ('organizations', '0004_alter_organization_helpers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_organizations', to='accounts.membership', verbose_name='Manager'),
        ),
    ]
