# Generated by Django 4.0.6 on 2022-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_membershiptype_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_user_organization',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_group_organization',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'user'), name='unique_membership_organization_type_user'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'type', 'group'), name='unique_membership_organization_type_group'),
        ),
    ]
