# Generated by Django 4.0.6 on 2022-08-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_membershiptype_only_one_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='helpers',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='managers',
        ),
    ]
