# Generated by Django 4.0.6 on 2022-08-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_helpers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'default_permissions': (), 'ordering': ['organization', '-admin', '-default', 'name']},
        ),
    ]
