# Generated by Django 4.0.6 on 2022-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_membershiptype_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershiptype',
            name='admin_not_default',
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='admin',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='default',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Default'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(('admin', False), _negated=True), name='admin_true_or_null'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(('default', False), _negated=True), name='default_true_or_null'),
        ),
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin', True), ('default__isnull', True)), ('admin__isnull', True), _connector='OR'), name='admin_not_default'),
        ),
    ]
