# Generated by Django 4.0.6 on 2022-08-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_membershiptype_admin_not_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.membershiptype', verbose_name='Membership Type'),
        ),
    ]
