repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--auto-fix]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: forbid-submodules
      - id: no-commit-to-branch
      - id: detect-private-key
  - repo: https://github.com/crate-ci/typos
    rev: v1.44.0
    hooks:
      - id: typos
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.93.8
    hooks:
      - id: trufflehog
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: <latest tag>
    hooks:
      - id: commitlint
        stages: [commit-msg]
