# Generated by Django 4.0.6 on 2022-07-23 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shiftings.utils.fields.date_time
import shiftings.utils.time.month
import shiftings.utils.time.week


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('required_shifters', models.PositiveIntegerField(default=0, verbose_name='Required Shifters')),
                ('max_shifters', models.PositiveIntegerField(default=0, verbose_name='Maximum Shifters')),
                ('additional_infos', models.TextField(blank=True, null=True, verbose_name='Additional Infos')),
                ('time_frame_field', models.PositiveSmallIntegerField(choices=[(1, 'Nth [weekday] of each month'), (2, 'Nth day of each month'), (3, 'every Nth [weekday]'), (4, 'Nth workday of each month'), (5, 'Nth day of [month]'), (6, 'Nth workday of [month]')], verbose_name='Timeframe Type')),
                ('ordinal', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('week_day_field', shiftings.utils.time.week.WeekDayField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Day of the Week')),
                ('month_field', shiftings.utils.time.month.MonthField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('first_occurrence', shiftings.utils.fields.date_time.DateField(verbose_name='First Occurrence')),
                ('time', shiftings.utils.fields.date_time.TimeField(verbose_name='Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('weekend_handling_field', models.PositiveSmallIntegerField(choices=[(1, 'ignore'), (2, 'cancel'), (3, 'show warning')], default=1, verbose_name='Weekend problem handling')),
                ('weekend_warning', models.TextField(blank=True, null=True, verbose_name='Warning text for weekend')),
                ('holiday_handling_field', models.PositiveSmallIntegerField(choices=[(1, 'ignore'), (2, 'cancel'), (3, 'show warning')], default=1, verbose_name='Holidays problem handling')),
                ('holiday_warning', models.TextField(blank=True, null=True, verbose_name='Warning text for holidays')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('required_shifters', models.PositiveIntegerField(default=0, verbose_name='Required Shifters')),
                ('max_shifters', models.PositiveIntegerField(default=0, verbose_name='Maximum Shifters')),
                ('additional_infos', models.TextField(blank=True, null=True, verbose_name='Additional Infos')),
                ('start', models.DateTimeField(db_index=True, verbose_name='Start Date and Time')),
                ('end', models.DateTimeField(db_index=True, verbose_name='End Date and Time')),
                ('locked', models.BooleanField(default=False, verbose_name='Locked for Participation')),
                ('warnings', models.TextField(verbose_name='Warning')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to='shifts.recurringshift', verbose_name='Created by Recurring Shift')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Created by Shifter')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shifttype', verbose_name='Shift Type')),
                ('shifters', models.ManyToManyField(blank=True, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Shifters')),
            ],
            options={
                'ordering': ['start', 'end', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shifttype', verbose_name='Shift Type'),
        ),
    ]
