# Generated by Django 4.0.6 on 2022-08-05 15:51

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import shiftings.utils.fields.date_time
import shiftings.utils.time.month
import shiftings.utils.time.week


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Display Name is optional', max_length=100, null=True, verbose_name='Display Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['display_name', 'user'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RecurringShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('required_users', models.PositiveIntegerField(default=0, verbose_name='Required User')),
                ('max_users', models.PositiveIntegerField(default=0, verbose_name='Maximum User')),
                ('additional_infos', models.TextField(blank=True, null=True, verbose_name='Additional Infos')),
                ('time_frame_field', models.PositiveSmallIntegerField(choices=[(1, 'Nth [weekday] of each month'), (2, 'Nth day of each month'), (3, 'every Nth [weekday]'), (4, 'Nth workday of each month'), (5, 'Nth day of [month]'), (6, 'Nth workday of [month]')], verbose_name='Timeframe Type')),
                ('ordinal', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('week_day_field', shiftings.utils.time.week.WeekDayField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Day of the Week')),
                ('month_field', shiftings.utils.time.month.MonthField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('first_occurrence', shiftings.utils.fields.date_time.DateField(verbose_name='First Occurrence')),
                ('time', shiftings.utils.fields.date_time.TimeField(verbose_name='Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('weekend_handling_field', models.PositiveSmallIntegerField(choices=[(1, 'ignore'), (2, 'cancel'), (3, 'show warning')], default=1, verbose_name='Weekend problem handling')),
                ('weekend_warning', models.TextField(blank=True, null=True, verbose_name='Warning text for weekend')),
                ('holiday_handling_field', models.PositiveSmallIntegerField(choices=[(1, 'ignore'), (2, 'cancel'), (3, 'show warning')], default=1, verbose_name='Holidays problem handling')),
                ('holiday_warning', models.TextField(blank=True, null=True, verbose_name='Warning text for holidays')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'ordering': ['name', 'organization'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShiftGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('position', models.PositiveSmallIntegerField()),
                ('color', colorfield.fields.ColorField(default='#FD7E14', image_field=None, max_length=18, samples=[('#0D6EFD', 'Blue'), ('#6610F2', 'Indigo'), ('#6F42C1', 'Purple'), ('#D63384', 'Pink'), ('#DC3545', 'Red'), ('#FD7E14', 'Orange'), ('#FFC107', 'Yellow'), ('#198754', 'Green'), ('#20C997', 'Teal'), ('#0DCAF0', 'Cyan')])),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_groups', to='events.event', verbose_name='Event')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_groups', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'ordering': ['position', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('required_users', models.PositiveIntegerField(default=0, verbose_name='Required User')),
                ('max_users', models.PositiveIntegerField(default=0, verbose_name='Maximum User')),
                ('additional_infos', models.TextField(blank=True, null=True, verbose_name='Additional Infos')),
                ('start', shiftings.utils.fields.date_time.DateTimeField(db_index=True, verbose_name='Start Date and Time')),
                ('end', shiftings.utils.fields.date_time.DateTimeField(db_index=True, verbose_name='End Date and Time')),
                ('locked', models.BooleanField(default=False, verbose_name='Locked for Participation')),
                ('warnings', models.TextField(blank=True, null=True, verbose_name='Warning')),
                ('created', shiftings.utils.fields.date_time.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', shiftings.utils.fields.date_time.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to='shifts.recurringshift', verbose_name='Created by Recurring Shift')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='events.event', verbose_name='Event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='Organization')),
                ('participants', models.ManyToManyField(blank=True, related_name='shift_set', to='shifts.participant', verbose_name='Users')),
                ('shift_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftgroup', verbose_name='Shift Group')),
            ],
            options={
                'ordering': ['start', 'end', 'name', 'organization'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='shift_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftgroup', verbose_name='Shift Group'),
        ),
        migrations.CreateModel(
            name='OrganizationSummarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_time_range_type', models.PositiveSmallIntegerField(choices=[(1, 'Month'), (2, 'Quarter'), (3, 'Half Year'), (4, 'Year'), (5, 'Decade'), (6, 'Century'), (7, 'Millennium')], default=3, verbose_name='Default time range for summary')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_settings', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'position'), name='shift_group_organization_position_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(fields=('event', 'position'), name='shift_group_event_position_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='shift_group_organization_name_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='shift_group_event_name_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event__isnull', False), ('organization__isnull', True)), models.Q(('event__isnull', True), ('organization__isnull', False)), _connector='OR'), name='shift_group_name_or_organization'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.expressions.F('end'))), name='shift_start_before_end'),
        ),
    ]
