# Generated by Django 4.0.9 on 2023-04-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Whether the participant has taken part in the shift or not. Default: False', verbose_name='Participation confirmed'),
        ),
    ]
