# Generated by Django 4.0.6 on 2023-01-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttype',
            options={'default_permissions': (), 'ordering': ['group', 'name']},
        ),
        migrations.AddField(
            model_name='organizationsummarysettings',
            name='other_shifts_group_name',
            field=models.CharField(default='Other', max_length=30, verbose_name='"Other" Shift Type Group Name'),
        ),
        migrations.CreateModel(
            name='ShiftTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_type_groups', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'ordering': ['organization', 'order'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='shifttype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_types', to='shifts.shifttypegroup', verbose_name='Group'),
        ),
        migrations.AddConstraint(
            model_name='shifttypegroup',
            constraint=models.UniqueConstraint(fields=('organization', 'order'), name='shift_type_group_organization_order_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shifttypegroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='shift_type_group_organization_name_unique_constraint'),
        ),
    ]
