# Generated by Django 4.0.6 on 2022-08-12 19:08

from django.db import migrations, models
import django.db.models.deletion
import shiftings.utils.fields.date_time


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringshift',
            options={'default_permissions': (), 'ordering': ['organization', 'name']},
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='additional_infos',
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='place',
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='required_users',
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='recurringshift',
            name='time',
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='manually_disabled',
            field=models.BooleanField(default=False, verbose_name='Manuelly Disabled'),
        ),
        migrations.AlterField(
            model_name='recurringshift',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_shifts', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.CreateModel(
            name='ShiftTemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('start_time', shiftings.utils.fields.date_time.TimeField(db_index=True, verbose_name='Start Time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_delay', models.DurationField(verbose_name='Start Delay')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('required_users', models.PositiveIntegerField(default=0, verbose_name='Required User')),
                ('max_users', models.PositiveIntegerField(default=0, verbose_name='Maximum User')),
                ('additional_infos', models.TextField(blank=True, null=True, verbose_name='Additional Infos')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.shifttemplategroup', verbose_name='Template Group')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shifttype', verbose_name='Shift Type')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_shifts', to='shifts.shifttemplategroup', verbose_name='Shift Template'),
        ),
    ]
