# Generated by Django 4.0.6 on 2023-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsummarysettings',
            name='default_shift_types',
            field=models.JSONField(blank=True, null=True, verbose_name='Shift Summary Shift Types'),
        ),
    ]
