# Generated by Django 4.0.6 on 2022-07-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
        ('shifts', '0002_alter_recurringshift_place_alter_shift_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='created_by',
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
    ]
