# Generated by Django 4.0.6 on 2022-07-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_website_and_more'),
        ('shifts', '0002_alter_shifttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_groups', to='organizations.organization')),
                ('shift_types', models.ManyToManyField(to='shifts.shifttype', verbose_name='Shift Types')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'position'), name='shift_group_position_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shiftgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='shift_group_name_unique_constraint'),
        ),
    ]
