# Generated by Django 4.0.9 on 2023-04-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0002_organization_confirm_participation_active'),
        ('shifts', '0002_participant_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_object_id', models.BigIntegerField()),
                ('permission_type_field', models.PositiveSmallIntegerField(choices=[(0, 'Nothing'), (1, 'See Shift exists'), (2, 'See Shift Details'), (3, 'See Shift Participants'), (4, 'Participate')], verbose_name='Permission Type')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation_permissions', to='organizations.organization', verbose_name='Affected Organization')),
                ('referred_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='participationpermission',
            index=models.Index(fields=['referred_content_type', 'referred_object_id'], name='referred_object_index'),
        ),
        migrations.AddConstraint(
            model_name='participationpermission',
            constraint=models.UniqueConstraint(fields=('referred_content_type', 'referred_object_id', 'organization'), name='organization_unique_per_referred_object'),
        ),
    ]
