# Generated by Django 4.0.6 on 2022-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_shift_created_by_recurringshift_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringshift',
            options={'default_permissions': (), 'ordering': ['name', 'organization']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'default_permissions': (), 'ordering': ['start', 'end', 'name', 'organization']},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'default_permissions': (), 'ordering': ['name']},
        ),
    ]
