# Generated by Django 4.0.6 on 2022-07-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_website_and_more'),
        ('shifts', '0003_shiftgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftgroup',
            options={'default_permissions': (), 'ordering': ['position']},
        ),
        migrations.CreateModel(
            name='OrganizationSummarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_time_range', models.PositiveSmallIntegerField(choices=[(1, 'Month'), (2, 'Quarter'), (3, 'Half Year'), (4, 'Year'), (5, 'Decade'), (6, 'Century'), (7, 'Millennium')], default=3, verbose_name='Default time range for summary')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_settings', to='organizations.organization')),
            ],
        ),
    ]
