# Generated by Django 4.0.9 on 2023-02-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_organizationsummarysettings_default_shift_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringshift',
            name='manually_disabled',
            field=models.BooleanField(default=False, verbose_name='Manually Disabled'),
        ),
    ]
