# Generated by Django 4.0.9 on 2023-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_participationpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationpermission',
            name='permission_type_field',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Permission'), (1, 'See Shift exists'), (2, 'See Shift Details'), (3, 'See Shift Participants'), (4, 'Participate')], verbose_name='Permission Type'),
        ),
    ]
