# Generated by Django 4.0.6 on 2022-07-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_shiftgroup_options_organizationsummarysettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsummarysettings',
            old_name='default_time_range',
            new_name='default_time_range_type',
        ),
    ]
