# Generated by Django 4.0.9 on 2023-04-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_confirm_participation_active'),
        ('shifts', '0004_alter_participationpermission_permission_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationpermission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_participation_permissions', to='organizations.organization', verbose_name='Affected Organization'),
        ),
    ]
