# Generated by Django 4.0.9 on 2023-02-21 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_recurringshift_manually_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='max_users',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(64)], verbose_name='Maximum Users'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='required_users',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32)], verbose_name='Required Users'),
        ),
    ]
