# Generated by Django 4.0.6 on 2022-07-23 18:02

from django.db import migrations
import shiftings.utils.fields.date_time


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_recurringshift_options_alter_shift_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=shiftings.utils.fields.date_time.DateTimeField(db_index=True, verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=shiftings.utils.fields.date_time.DateTimeField(db_index=True, verbose_name='Start Date and Time'),
        ),
    ]
