# Generated by Django 4.0.6 on 2023-01-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_membershiptype_options'),
        ('shifts', '0004_alter_shifttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplategroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_template_groups', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
