# Generated by Django 4.0.9 on 2023-12-21 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_participationpermission_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringshift',
            name='auto_create_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='How many days in advance should the shifts be created?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)], verbose_name='Auto create days'),
        ),
    ]
