# Generated by Django 4.0.6 on 2023-01-25 22:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_shifttemplategroup_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringshift',
            name='color',
            field=colorfield.fields.ColorField(default='#FD7E14', image_field=None, max_length=18, samples=[('#0D6EFD', 'Blue'), ('#6610F2', 'Indigo'), ('#6F42C1', 'Purple'), ('#D63384', 'Pink'), ('#DC3545', 'Red'), ('#FD7E14', 'Orange'), ('#FFC107', 'Yellow'), ('#198754', 'Green'), ('#20C997', 'Teal'), ('#0DCAF0', 'Cyan')]),
        ),
    ]
