# Generated by Django 4.0.9 on 2023-02-23 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_shift_max_users_alter_shift_required_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringshift',
            name='holiday_warning',
            field=models.TextField(blank=True, help_text='A maximum of 250 characters is allowed', max_length=250, null=True, verbose_name='Warning text for holidays'),
        ),
        migrations.AlterField(
            model_name='recurringshift',
            name='weekend_warning',
            field=models.TextField(blank=True, help_text='A maximum of 250 characters is allowed', max_length=250, null=True, verbose_name='Warning text for weekend'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='additional_infos',
            field=models.TextField(blank=True, help_text='A maximum of 1000 characters is allowed', max_length=1000, null=True, verbose_name='Additional Infos'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=0, help_text='A maximum of 64 users can be present', validators=[django.core.validators.MaxValueValidator(64)], verbose_name='Maximum Users'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='required_users',
            field=models.PositiveSmallIntegerField(default=0, help_text='A maximum of 32 users can be required', validators=[django.core.validators.MaxValueValidator(32)], verbose_name='Required Users'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='warnings',
            field=models.TextField(blank=True, help_text='A maximum of 500 characters is allowed', max_length=500, null=True, verbose_name='Warning'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='additional_infos',
            field=models.TextField(blank=True, help_text='A maximum of 1000 characters is allowed', max_length=1000, null=True, verbose_name='Additional Infos'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=0, help_text='A maximum of 64 users can be present', validators=[django.core.validators.MaxValueValidator(64)], verbose_name='Maximum User'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='required_users',
            field=models.PositiveSmallIntegerField(default=0, help_text='A maximum of 32 users can be required', validators=[django.core.validators.MaxValueValidator(32)], verbose_name='Required User'),
        ),
    ]
