# Generated by Django 4.0.6 on 2022-07-30 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0005_rename_default_time_range_organizationsummarysettings_default_time_range_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='users',
        ),
        migrations.CreateModel(
            name='ShiftParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['display_name', 'user'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='participants',
            field=models.ManyToManyField(blank=True, to='shifts.shiftparticipation', verbose_name='Users'),
        ),
    ]
