# Generated by Django 6.0.2 on 2026-06-23 12:17

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0006_recurringshift_auto_create_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttype",
            name="is_mandatory",
            field=models.BooleanField(
                default=False,
                help_text="When set, members who do not respond to shifts of this type incur the organisation-wide no-response penalty. Only takes effect when the organisation has Session Points enabled.",
                verbose_name="Mandatory Shift Type",
            ),
        ),
        migrations.AddField(
            model_name="shifttype",
            name="point_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Points awarded when attending a shift of this type. Only takes effect when the organisation has Session Points enabled.",
                max_digits=4,
                verbose_name="Session Points Weight",
            ),
        ),
    ]
