# Generated by Django 4.0.6 on 2022-07-30 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0006_remove_shift_users_shiftparticipation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftParticipation',
            new_name='Participant',
        ),
    ]
