# Generated by Django 4.0.6 on 2022-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_rename_shiftparticipation_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='shift', to='shifts.participant', verbose_name='Users'),
        ),
    ]
