# Generated by Django 6.0.2 on 2026-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("shifts", "0007_shifttype_attendance_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="excused_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="excused_from_shifts",
                to="accounts.baseuser",
                verbose_name="Excused Users",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="is_mandatory_override",
            field=models.BooleanField(
                blank=True,
                help_text="If set, overrides the shift type mandatory flag just for this shift. Leave empty to inherit from the shift type.",
                null=True,
                verbose_name="Mandatory Override",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="point_weight_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="If set, overrides the shift type weight just for this shift. Leave empty to inherit from the shift type.",
                max_digits=4,
                null=True,
                verbose_name="Session Points Weight Override",
            ),
        ),
    ]
