# Generated by Django 6.0.2 on 2026-06-23 12:20

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0008_shift_attendance_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsummarysettings",
            name="attendance_points_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable per-member Session Points tracking on the shift summary and the shift detail page.",
                verbose_name="Session Points enabled",
            ),
        ),
        migrations.AddField(
            model_name="organizationsummarysettings",
            name="no_response_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.33"),
                help_text="Points deducted when a member does not respond to a mandatory shift. Applies organisation-wide.",
                max_digits=4,
                verbose_name="No-Response Penalty",
            ),
        ),
    ]
