# Generated by Django 4.0.6 on 2022-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_alter_participant_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='shift_set', to='shifts.participant', verbose_name='Users'),
        ),
    ]
