# Generated by Django 4.0.6 on 2022-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_alter_shift_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display Name is optional', max_length=100, null=True, verbose_name='Display Name'),
        ),
    ]
