# Generated by Django 4.0.6 on 2022-08-04 13:30

from django.db import migrations, models
import shiftings.utils.fields.date_time


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_alter_shift_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='created',
            field=shiftings.utils.fields.date_time.DateTimeField(auto_now_add=True, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='modified',
            field=shiftings.utils.fields.date_time.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display Name is optional', max_length=100, null=True, verbose_name='Display Name'),
        ),
    ]
