# Generated by Django 4.0.6 on 2022-08-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_alter_participant_display_name'),
        ('shifts', '0010_shift_created_shift_modified_and_more'),
    ]

    operations = [
    ]
