# Generated by Django 4.0.6 on 2022-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_membership_type'),
        ('shifts', '0011_merge_20220804_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftGroup',
            new_name='ShiftTypeGroup',
        ),
        migrations.RemoveConstraint(
            model_name='shifttypegroup',
            name='shift_group_position_unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='shifttypegroup',
            name='shift_group_name_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='shifttypegroup',
            constraint=models.UniqueConstraint(fields=('organization', 'position'), name='shift_type_group_position_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shifttypegroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='shift_type_group_name_unique_constraint'),
        ),
    ]
