# Generated by Django 4.0.6 on 2022-08-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_membership_type'),
        ('shifts', '0012_rename_shiftgroup_shifttypegroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttypegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_type_groups', to='organizations.organization'),
        ),
    ]
