# Generated by Django 4.0.6 on 2022-08-05 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_organizations',
            field=models.ManyToManyField(help_text='Organizations which are allowed to participate', to='organizations.organization', verbose_name='Allowed Organizations'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.expressions.F('end_date'))), name='event_start_after_end'),
        ),
    ]
