# Generated by Django 4.0.9 on 2023-04-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allowed_organizations',
        ),
        migrations.RemoveField(
            model_name='event',
            name='public',
        ),
    ]
