# Generated by Django 4.0.6 on 2022-07-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_organizations',
            field=models.ManyToManyField(help_text='Organizations which are allowed to participate', to='organizations.organization', verbose_name='Allowed Organizations'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
