# Generated by Django 4.2.9 on 2026-01-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'ordering': ['display_name', 'username']},
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('email', 'Email')], default='', help_text='Leave this empty to disable reminders.', max_length=32, verbose_name='Reminder Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='reminders_days_before_event',
            field=models.IntegerField(default=1, help_text='I want to receive reminders this many days before an event.', verbose_name='Days before event reminders'),
        ),
    ]
