# Generated by Django 6.0.2 on 2026-03-15 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCOfflineToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_offline_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
