# Generated by Django 4.0.9 on 2024-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ical_token',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='iCalendar Token'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ical_token'], name='user_ical_token_idx'),
        ),
    ]
