# Generated by Django 4.0.6 on 2022-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'default_permissions': (), 'ordering': ['group', 'shifter']},
        ),
        migrations.AlterModelOptions(
            name='shifter',
            options={'default_permissions': (), 'ordering': ['username']},
        ),
    ]
