# Generated by Django 6.0.2 on 2026-04-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'ordering': ['display_name', 'username']},
        ),
        migrations.CreateModel(
            name='FailedTokenAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='User ID if identifiable', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of failed attempt')),
                ('reason', models.CharField(choices=[('invalid_token', 'Invalid Token'), ('expired_token', 'Expired Token'), ('invalid_uid', 'Invalid User ID'), ('user_not_found', 'User Not Found'), ('already_used', 'Token Already Used'), ('other', 'Other')], default='other', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Failed Token Attempt',
                'verbose_name_plural': 'Failed Token Attempts',
                'ordering': ['-attempted_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='accounts_fa_ip_addr_44323c_idx'), models.Index(fields=['user_id', 'attempted_at'], name='accounts_fa_user_id_e177ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='User ID (allows tracking even after user deletion)')),
                ('token_hash', models.CharField(help_text='SHA256 hash of the token for secure storage', max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('email_confirm', 'Email Confirmation'), ('password_reset', 'Password Reset')], help_text='Type of token', max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When token was used')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that used token', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent that used token', null=True)),
            ],
            options={
                'verbose_name': 'Token Usage Log',
                'verbose_name_plural': 'Token Usage Logs',
                'ordering': ['-used_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['token_hash'], name='accounts_to_token_h_d6bccb_idx'), models.Index(fields=['user_id', 'token_type'], name='accounts_to_user_id_45f3d7_idx'), models.Index(fields=['used_at'], name='accounts_to_used_at_293c2f_idx')],
            },
        ),
    ]
