---
name: 'Dependency Check'

on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
